apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvitop-exporter
  namespace: monitoring
  labels:
    app: nvitop-exporter
    component: gpu-monitoring
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: nvitop-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace 