apiVersion: v1
kind: Service
metadata:
  name: nvitop-exporter
  namespace: monitoring
  labels:
    app: nvitop-exporter
    component: gpu-monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for DaemonSet
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: nvitop-exporter 