name: 🐛 Bug Report
description: File an issue about a bug.
title: "[BUG] "
labels: [bug]
assignees: [XuehaiPan]
body:
  - type: markdown
    attributes:
      value: |
        Please do your best to make the issue as easy to act on as possible, and only submit here if there is clearly a problem with `nvitop`.
        You may try the latest version of `nvitop` in an isolated environment with the following commands first:

        ```bash
        pip3 install --upgrade uv
        PYTHONFAULTHANDLER=1 uvx --from git+https://github.com/XuehaiPan/nvitop.git nvitop
        ```

  - type: checkboxes
    id: steps
    attributes:
      label: Required prerequisites
      description: Make sure you've completed the following steps before submitting your issue -- thank you!
      options:
        - label: I have read the documentation <https://nvitop.readthedocs.io>.
          required: true
        - label: I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
          required: true
        - label: I have tried the latest version of nvitop in a new isolated virtual environment.
          required: false

  - type: input
    id: version
    attributes:
      label: What version of nvitop are you using?
      description: Run command `nvitop --version` or `python3 -m nvitop --version` in your shell and paste the output here.
      placeholder: E.g., 1.0.0
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: Operating system and version
      placeholder: E.g., Ubuntu 20.04 LTS / Windows 10 Build 19043.1110
    validations:
      required: true

  - type: input
    id: driver-version
    attributes:
      label: NVIDIA driver version
      placeholder: E.g., 470.161.03
    validations:
      required: true

  - type: textarea
    id: nvidia-smi
    attributes:
      label: NVIDIA-SMI
      description: Run command `nvidia-smi` in your shell and paste the output here.
      render: text

  - type: textarea
    id: environment
    attributes:
      label: Python environment
      description: |
        Describe the characteristic of your environment:

        - Describe how the library was installed (pip, conda, source, ...)
        - Python version
        - Versions of any other relevant libraries

        Run the following command (copy all of them) in your shell and paste the results in the textbox below.

        ```bash
        python3 -m pip freeze | python3 -c 'import sys; print(sys.version, sys.platform); print("".join(filter(lambda s: any(word in s.lower() for word in ("nvi", "cuda", "nvml", "gpu")), sys.stdin)))'
        ```
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: >-
        Provide a short description, state the expected behavior and what actually happens. Include
        relevant information like what version of nvitop you are using, what system you are on, and
        any useful commands / output.
      placeholder: Describe what the problem is.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Steps to Reproduce
      description: >-
        The code should be minimal, have minimal external dependencies, and isolate the functions
        that cause breakage. Submit matched and complete snippets that can be easily run to diagnose
        the issue.
      value: |
        The Python snippets (if any):

        ```python

        ```

        Command lines:

        ```bash

        ```
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Traceback
      description: Put the Python traceback information here.
      placeholder: |
        Traceback (most recent call last):
          File ...
      render: pytb

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Run nvitop with `PYTHONFAULTHANDLER=1 LOGLEVEL=DEBUG nvitop` and paste the output here.
      render: text

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here. Screenshots may also be helpful.

        If you know or suspect the reason for this bug, paste the code lines and suggest modifications.
