name: ✨ Feature Request
description: Suggest an idea for this project.
title: "[Feature Request] "
labels: [enhancement]
assignees: [XuehaiPan]
body:
  - type: markdown
    attributes:
      value: |
        Please do your best to make the issue as easy to act on as possible, and only submit here if there is clearly a problem with `nvitop`.
        You may try the latest version of `nvitop` in an isolated environment with the following commands first:

        ```bash
        pip3 install --upgrade uv
        PYTHONFAULTHANDLER=1 uvx --from git+https://github.com/XuehaiPan/nvitop.git nvitop
        ```

  - type: checkboxes
    id: steps
    attributes:
      label: Required prerequisites
      description: Make sure you've completed the following steps before submitting your issue -- thank you!
      options:
        - label: I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
          required: true
        - label: I have tried the latest version of nvitop in a new isolated virtual environment.
          required: false

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Outline the motivation for the proposal.
      value: |
        <!-- Please outline the motivation for the proposal.
        Is your feature request related to a problem? E.g., "I'm always frustrated when [...]".
        If this is related to another issue, please link here too. -->
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Provide a clear and concise description of what you want to happen.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. Screenshots may also be helpful.
