name: Build and Publish nvitop-exporter

on:
  push:
    paths:
      - 'nvitop-exporter/**'
  pull_request:
    paths:
      - setup.py
      - setup.cfg
      - pyproject.toml
      - MANIFEST.in
      - nvitop/version.py
      - 'nvitop-exporter/**'
  release:
    types:
      - published
  workflow_dispatch:  # Allow manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nvitop

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t test-image:latest ./nvitop-exporter

      - name: Test Docker image
        run: |
          docker run --rm test-image:latest --help

      - name: Login and push Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

          # Determine tag based on ref type
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            # Release tag (e.g., refs/tags/v1.0.0 -> exporter-v1.0.0)
            VERSION=${GITHUB_REF#refs/tags/}
            TAG="exporter-${VERSION}"
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            # Branch (e.g., refs/heads/k8s -> exporter-k8s)
            BRANCH=${GITHUB_REF#refs/heads/}
            TAG="exporter-${BRANCH}"
          else
            # Fallback for other ref types
            TAG="exporter-${GITHUB_SHA::8}"
          fi

          IMAGE_FULL_NAME="${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${TAG}"

          echo "Tagging and pushing: ${IMAGE_FULL_NAME}"
          docker tag test-image:latest "${IMAGE_FULL_NAME}"
          docker push "${IMAGE_FULL_NAME}"
